title = "JesusMtnez"

defaultContentLanguage = "en"
languageCode = "en"

enableEmoji = true

theme = "Coder"

paginate = 20
canonifyUrls = true

[markup.highlight]
  codeFences = true
  lineNoStart = 1
  lineNos = true
  tabWith = 2
  style = "onedark"
  noClasses = true

[markup.goldmark.renderer]
  unsafe = true

[params]
  author = "Jesús Martínez-B. H."
  description = "JesusMtnez's personal web"
  keywords = "blog,developer,personal"
  info = "Scala developer & Functional programmer enthusiast & DevOps"
  avatarUrl = "images/profile.jpeg"
  #footerContent = "Enter a text here."
  since = "2017"
  colorScheme = "dark"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  hideCredits = false
  hideCopyright = false
  hideColorSchemeToggle = false

  math = true

[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 2
    url = "https://github.com/JesusMtnez"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-2x fa-gitlab"
    weight = 1
    url = "https://gitlab.com/JesusMtnez"
[[params.social]]
    name = "Codeberg.org"
    icon = "fa fa-2x fa-git-square"
    weight = 2
    url = "https://codeberg.org/JesusMtnez"
[[params.social]]
    name = "Mastodon"
    icon = "fa fa-2x fa-mastodon"
    weight = 3
    url = "https://fosstodon.org/@jesusmtnez"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-2x fa-twitter"
    weight = 3
    url = "https://twitter.com/JesusMtnezBH/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/JesusMtnez/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Resume"
    weight = 2
    url = "/resume/"
# [[menu.main]]
#     name = "About"
#     weight = 3
#     url = "/about/"
